---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    labels:
      provider: fabric8
      project: che
      version: 1.0.15
      group: io.fabric8.online.apps
    name: che
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      fabric8.io/app-menu: development
      fabric8.io/git-commit: 89db9d578a39d3010313e7730ec968dc55582666
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-online/master/apps/che/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v1.0.15
    labels:
      project: che
      provider: fabric8
      expose: "true"
      version: 1.0.15
      group: io.fabric8.online.apps
    name: che
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: che
      provider: fabric8
      group: io.fabric8.online.apps
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: standard
    labels:
      provider: fabric8
      project: che
      version: 1.0.15
      group: io.fabric8.online.apps
    name: che-conf-volume
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      volume.beta.kubernetes.io/storage-class: standard
    labels:
      provider: fabric8
      project: che
      version: 1.0.15
      group: io.fabric8.online.apps
    name: che-data-volume
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      provider: fabric8
      project: che
      version: 1.0.15
      group: io.fabric8.online.apps
    name: che
  data:
    hostname-http: che.openshift.mini
    workspace-storage: /home/user/che/workspaces
    workspace-storage-create-folders: "false"
    local-conf-dir: /etc/conf
    openshift-endpoint: https://192.168.42.234:8443/
    openshift-token: ""
    openshift-username: openshift-dev
    openshift-password: devel
    openshift-project: eclipse-che
    openshift-serviceaccountname: che
    che-server-evaluation-strategy: docker-local
    log-level: INFO
    docker-connector: openshift
    port: "8080"
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/git-commit: 89db9d578a39d3010313e7730ec968dc55582666
      fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-online/master/apps/che/src/main/fabric8/icon.png
      fabric8.io/git-branch: release-v1.0.15
      fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=che&var-version=1.0.15
    labels:
      provider: fabric8
      project: che
      version: 1.0.15
      group: io.fabric8.online.apps
    name: che
  spec:
    replicas: 1
    selector:
      project: che
      provider: fabric8
      group: io.fabric8.online.apps
    strategy:
      rollingParams:
        timeoutSeconds: 10800
      type: Rolling
    template:
      metadata:
        annotations:
          fabric8.io/git-commit: 89db9d578a39d3010313e7730ec968dc55582666
          fabric8.io/iconUrl: https://cdn.rawgit.com/fabric8io/fabric8-online/master/apps/che/src/main/fabric8/icon.png
          fabric8.io/git-branch: release-v1.0.15
          fabric8.io/metrics-path: dashboard/file/kubernetes-pods.json/?var-project=che&var-version=1.0.15
          pod.alpha.kubernetes.io/init-containers: '[{"image":"busybox","imagePullPolicy":"IfNotPresent","name":"init","command":["chmod","777","/conf","/data"],"volumeMounts":[{"mountPath":"/conf","name":"che-conf-volume"},{"mountPath":"/data","name":"che-data-volume"}]}]'
        labels:
          provider: fabric8
          project: che
          version: 1.0.15
          group: io.fabric8.online.apps
      spec:
        containers:
        - env:
          - name: CHE_DOCKER_IP_EXTERNAL
            valueFrom:
              configMapKeyRef:
                key: hostname-http
                name: che
          - name: CHE_WORKSPACE_STORAGE
            valueFrom:
              configMapKeyRef:
                key: workspace-storage
                name: che
          - name: CHE_WORKSPACE_STORAGE_CREATE_FOLDERS
            valueFrom:
              configMapKeyRef:
                key: workspace-storage-create-folders
                name: che
          - name: CHE_LOCAL_CONF_DIR
            valueFrom:
              configMapKeyRef:
                key: local-conf-dir
                name: che
          - name: CHE_OPENSHIFT_ENDPOINT
            valueFrom:
              configMapKeyRef:
                key: openshift-endpoint
                name: che
          - name: CHE_OPENSHIFT_TOKEN
            valueFrom:
              configMapKeyRef:
                key: openshift-token
                name: che
          - name: CHE_OPENSHIFT_USERNAME
            valueFrom:
              configMapKeyRef:
                key: openshift-username
                name: che
          - name: CHE_OPENSHIFT_PASSWORD
            valueFrom:
              configMapKeyRef:
                key: openshift-password
                name: che
          - name: CHE_OPENSHIFT_PROJECT
            valueFrom:
              configMapKeyRef:
                key: openshift-project
                name: che
          - name: CHE_OPENSHIFT_SERVICEACCOUNTNAME
            valueFrom:
              configMapKeyRef:
                key: openshift-serviceaccountname
                name: che
          - name: CHE_DOCKER_SERVER__EVALUATION__STRATEGY
            valueFrom:
              configMapKeyRef:
                key: che-server-evaluation-strategy
                name: che
          - name: CHE_LOG_LEVEL
            valueFrom:
              configMapKeyRef:
                key: log-level
                name: che
          - name: CHE_PORT
            valueFrom:
              configMapKeyRef:
                key: port
                name: che
          - name: CHE_DOCKER_CONNECTOR
            valueFrom:
              configMapKeyRef:
                key: docker-connector
                name: che
          image: rhche/che-server:nightly
          imagePullPolicy: IfNotPresent
          livenessProbe:
            initialDelaySeconds: 120
            tcpSocket:
              port: 8080
            timeoutSeconds: 10
          name: che
          ports:
          - containerPort: 8080
            name: http
          readinessProbe:
            initialDelaySeconds: 20
            tcpSocket:
              port: 8080
            timeoutSeconds: 10
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /var/run/docker.sock
            name: docker
            readOnly: false
          - mountPath: /conf
            name: che-conf-volume
            readOnly: false
          - mountPath: /data
            name: che-data-volume
        serviceAccountName: che
        volumes:
        - hostPath:
            path: /var/run/docker.sock
          name: docker
        - name: che-conf-volume
          persistentVolumeClaim:
            claimName: che-conf-volume
        - name: che-data-volume
          persistentVolumeClaim:
            claimName: che-data-volume
    triggers:
    - type: ConfigChange
